/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    AddModelCard: typeof import('./src/components/AddModelCard/index.vue')['default']
    Barchats: typeof import('./src/components/echarts/barchats/index.vue')['default']
    Echarts: typeof import('./src/components/echarts/index.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    ItemCard: typeof import('./src/components/ItemCard/index.vue')['default']
    LineCharts: typeof import('./src/components/echarts/lineCharts/index.vue')['default']
    ModelUploadDialog: typeof import('./src/components/ModelUploadDialog/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Svgicon: typeof import('./src/components/Svgicon/index.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    ThreeDScene: typeof import('./src/components/ThreeDScene.vue')['default']
    ThreeModel: typeof import('./src/components/three/threeModel.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
